package DoodleProject;


/**
* DoodleProject/DoodleHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* lunedì 4 giugno 2012 15.44.47 CEST
*/

abstract public class DoodleHelper
{
  private static String  _id = "IDL:DoodleProject/Doodle:1.0";

  public static void insert (org.omg.CORBA.Any a, DoodleProject.Doodle that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DoodleProject.Doodle extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DoodleProject.DoodleHelper.id (), "Doodle");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DoodleProject.Doodle read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DoodleStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DoodleProject.Doodle value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DoodleProject.Doodle narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DoodleProject.Doodle)
      return (DoodleProject.Doodle)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DoodleProject._DoodleStub stub = new DoodleProject._DoodleStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DoodleProject.Doodle unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DoodleProject.Doodle)
      return (DoodleProject.Doodle)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DoodleProject._DoodleStub stub = new DoodleProject._DoodleStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
