package DoodleProject;


/**
* DoodleProject/DoodleManagerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* lunedì 4 giugno 2012 15.44.47 CEST
*/

public abstract class DoodleManagerPOA extends org.omg.PortableServer.Servant
 implements DoodleProject.DoodleManagerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerUser", new java.lang.Integer (0));
    _methods.put ("deleteUser", new java.lang.Integer (1));
    _methods.put ("getDoodle", new java.lang.Integer (2));
    _methods.put ("createNewDoodle", new java.lang.Integer (3));
    _methods.put ("getDoodleList", new java.lang.Integer (4));
    _methods.put ("closeDoodle", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DoodleProject/DoodleManager/registerUser
       {
         DoodleProject.DoodleClient client = DoodleProject.DoodleClientHelper.read (in);
         boolean $result = false;
         $result = this.registerUser (client);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // DoodleProject/DoodleManager/deleteUser
       {
         DoodleProject.DoodleClient client = DoodleProject.DoodleClientHelper.read (in);
         this.deleteUser (client);
         out = $rh.createReply();
         break;
       }

       case 2:  // DoodleProject/DoodleManager/getDoodle
       {
         String name = in.read_string ();
         DoodleProject.Doodle $result = null;
         $result = this.getDoodle (name);
         out = $rh.createReply();
         DoodleProject.DoodleHelper.write (out, $result);
         break;
       }

       case 3:  // DoodleProject/DoodleManager/createNewDoodle
       {
         String name = in.read_string ();
         String owner = in.read_string ();
         DoodleProject.Doodle $result = null;
         $result = this.createNewDoodle (name, owner);
         out = $rh.createReply();
         DoodleProject.DoodleHelper.write (out, $result);
         break;
       }

       case 4:  // DoodleProject/DoodleManager/getDoodleList
       {
         String $result[] = null;
         $result = this.getDoodleList ();
         out = $rh.createReply();
         DoodleProject.listStringHelper.write (out, $result);
         break;
       }

       case 5:  // DoodleProject/DoodleManager/closeDoodle
       {
         DoodleProject.Doodle doodle = DoodleProject.DoodleHelper.read (in);
         int $result[] = null;
         $result = this.closeDoodle (doodle);
         out = $rh.createReply();
         DoodleProject.listIntegerHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DoodleProject/DoodleManager:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DoodleManager _this() 
  {
    return DoodleManagerHelper.narrow(
    super._this_object());
  }

  public DoodleManager _this(org.omg.CORBA.ORB orb) 
  {
    return DoodleManagerHelper.narrow(
    super._this_object(orb));
  }


} // class DoodleManagerPOA
