package DoodleProject;


/**
* DoodleProject/DoodleDetails.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* lunedì 4 giugno 2012 15.44.47 CEST
*/

public final class DoodleDetails implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String owner = null;

  public DoodleDetails ()
  {
  } // ctor

  public DoodleDetails (String _name, String _owner)
  {
    name = _name;
    owner = _owner;
  } // ctor

} // class DoodleDetails
