package DoodleProject;


/**
* DoodleProject/DoodleClientPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* lunedì 4 giugno 2012 15.44.47 CEST
*/

public abstract class DoodleClientPOA extends org.omg.PortableServer.Servant
 implements DoodleProject.DoodleClientOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("printMsg", new java.lang.Integer (0));
    _methods.put ("getUsername", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DoodleProject/DoodleClient/printMsg
       {
         String msg = in.read_string ();
         this.printMsg (msg);
         out = $rh.createReply();
         break;
       }

       case 1:  // DoodleProject/DoodleClient/getUsername
       {
         String $result = null;
         $result = this.getUsername ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DoodleProject/DoodleClient:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DoodleClient _this() 
  {
    return DoodleClientHelper.narrow(
    super._this_object());
  }

  public DoodleClient _this(org.omg.CORBA.ORB orb) 
  {
    return DoodleClientHelper.narrow(
    super._this_object(orb));
  }


} // class DoodleClientPOA
