package DoodleProject;


/**
* DoodleProject/DoodleClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* lunedì 4 giugno 2012 15.44.47 CEST
*/

public interface DoodleClientOperations 
{
  void printMsg (String msg);
  String getUsername ();
} // interface DoodleClientOperations
