package DoodleProject;


/**
* DoodleProject/DoodlePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* lunedì 4 giugno 2012 15.44.47 CEST
*/

public abstract class DoodlePOA extends org.omg.PortableServer.Servant
 implements DoodleProject.DoodleOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getChoices", new java.lang.Integer (0));
    _methods.put ("addChoice", new java.lang.Integer (1));
    _methods.put ("vote", new java.lang.Integer (2));
    _methods.put ("_get_details", new java.lang.Integer (3));
    _methods.put ("toString", new java.lang.Integer (4));
    _methods.put ("calculateWinner", new java.lang.Integer (5));
    _methods.put ("getVotingClients", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DoodleProject/Doodle/getChoices
       {
         String $result[] = null;
         $result = this.getChoices ();
         out = $rh.createReply();
         DoodleProject.listStringHelper.write (out, $result);
         break;
       }

       case 1:  // DoodleProject/Doodle/addChoice
       {
         String choice = in.read_string ();
         this.addChoice (choice);
         out = $rh.createReply();
         break;
       }

       case 2:  // DoodleProject/Doodle/vote
       {
         try {
           DoodleProject.DoodleClient client = DoodleProject.DoodleClientHelper.read (in);
           String choice = in.read_string ();
           int $result = (int)0;
           $result = this.vote (client, choice);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (DoodleProject.UserAlreadyVoted $ex) {
           out = $rh.createExceptionReply ();
           DoodleProject.UserAlreadyVotedHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // DoodleProject/Doodle/_get_details
       {
         DoodleProject.DoodleDetails $result = null;
         $result = this.details ();
         out = $rh.createReply();
         DoodleProject.DoodleDetailsHelper.write (out, $result);
         break;
       }

       case 4:  // DoodleProject/Doodle/_toString
       {
         String $result = null;
         $result = this._toString ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // DoodleProject/Doodle/calculateWinner
       {
         int $result[] = null;
         $result = this.calculateWinner ();
         out = $rh.createReply();
         DoodleProject.listIntegerHelper.write (out, $result);
         break;
       }

       case 6:  // DoodleProject/Doodle/getVotingClients
       {
         String $result[] = null;
         $result = this.getVotingClients ();
         out = $rh.createReply();
         DoodleProject.listStringHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DoodleProject/Doodle:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Doodle _this() 
  {
    return DoodleHelper.narrow(
    super._this_object());
  }

  public Doodle _this(org.omg.CORBA.ORB orb) 
  {
    return DoodleHelper.narrow(
    super._this_object(orb));
  }


} // class DoodlePOA
