package DoodleProject;

/**
* DoodleProject/DoodleHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* lunedì 4 giugno 2012 15.44.47 CEST
*/

public final class DoodleHolder implements org.omg.CORBA.portable.Streamable
{
  public DoodleProject.Doodle value = null;

  public DoodleHolder ()
  {
  }

  public DoodleHolder (DoodleProject.Doodle initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DoodleProject.DoodleHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DoodleProject.DoodleHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DoodleProject.DoodleHelper.type ();
  }

}
