package DoodleProject;


/**
* DoodleProject/listDoodleHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* lunedì 4 giugno 2012 14.49.25 CEST
*/

public final class listDoodleHolder implements org.omg.CORBA.portable.Streamable
{
  public DoodleProject.Doodle value[] = null;

  public listDoodleHolder ()
  {
  }

  public listDoodleHolder (DoodleProject.Doodle[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DoodleProject.listDoodleHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DoodleProject.listDoodleHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DoodleProject.listDoodleHelper.type ();
  }

}
