package DoodleProject;


/**
* DoodleProject/listIntegerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* lunedì 4 giugno 2012 15.44.47 CEST
*/

public final class listIntegerHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public listIntegerHolder ()
  {
  }

  public listIntegerHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DoodleProject.listIntegerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DoodleProject.listIntegerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DoodleProject.listIntegerHelper.type ();
  }

}
