package DoodleProject;


/**
* DoodleProject/UserAlreadyVoted.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* lunedì 4 giugno 2012 15.44.47 CEST
*/

public final class UserAlreadyVoted extends org.omg.CORBA.UserException
{

  public UserAlreadyVoted ()
  {
    super(UserAlreadyVotedHelper.id());
  } // ctor


  public UserAlreadyVoted (String $reason)
  {
    super(UserAlreadyVotedHelper.id() + "  " + $reason);
  } // ctor

} // class UserAlreadyVoted
